"""
Recommendation Engine Constants
"""


class RecommendationPriority:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationAction:
    HOLD = "HOLD"
    MAINTAIN = "MAINTAIN"
    MONITOR = "MONITOR"
    REBALANCE = "REBALANCE"
    REVIEW_STRUCTURE = "REVIEW STRUCTURE"
    REVIEW_POSITION_SIZES = "REVIEW POSITION SIZES"
    REDUCE_CONCENTRATION = "REDUCE CONCENTRATION"
    INCREASE_DIVERSIFICATION = "INCREASE DIVERSIFICATION"